spring:
    datasource:
        ur: jdbc:h2:mem:testdb
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
          ddl-auto: update
db:
    type: h2